from typing import Any, Optional

class Parser:
    def parse(self, input: Optional[str]=None, lexer: Any=None, debug: bool=False, tracking: bool=False, tokenfunc: Any=None, filename: Optional[str]=None) -> Any: ...

def yacc(start: Optional[str]=None, errorlog: Any=None) -> Parser: ...

class NullLogger(object): ...