"""
Forward-backward incremental induction (FBII) proof checker.

FBII is an incremental proof technique for establishing safety of a transition system.
A proof is a sequence of steps, each associating a set of invariants (the step
body) in a given direction (forward or backward). Steps are either simple or prophecy:

  Simple step (no `prophecy` keyword): verified by plain induction (2 SMT checks).
    Forward:  1. INIT & PREV => INV
              2. INV & TR & PREV & PREV' => INV'
    Backward: 1. BAD & PREV => INV
              2. INV' & TR & PREV & PREV' => INV

  Prophecy step (`prophecy` keyword): introduces a fresh mutable relation __M_P that holds on viable prophecy
    choices, to show that for every forward / backward trace there exists a choice of prophecy parameters such
    that the body invariants hold at every state. Verified by three SMT checks:

    Forward step (proves the body invariants hold for some prophecy "from init", if bad is reached):
      1. INIT_PROPH  =>  PROPH_INV        (initiation)
      2. PROPH_INV & TR_PROPH  =>  PROPH_INV'   (consecution, per transition)
      3. PROPH_INV  =>  !BAD_PROPH        (equivalent to BAD => there exists a prophecy satisfying the body invariants)

    Backward step (proves the body invariants hold for some prophecy "from bad", if init is reached):
      1. BAD_PROPH   =>  PROPH_INV        (initiation from bad)
      2. PROPH_INV' & TR_PROPH  =>  PROPH_INV   (consecution, per transition)
      3. PROPH_INV  =>  !INIT_PROPH       (equivalent to INIT => there exists a prophecy satisfying the body invariants)

    Where:
      INIT_PROPH = INIT & PREV & (forall P. __INV_P(P) -> __M_P(P)) [negated: INIT & PREV -> exists P. __INV_P(P) & !__M_P(P)]
      BAD_PROPH  = BAD  & PREV & (forall P. __INV_P(P) -> !__M_P(P)) [negated: BAD & PREV -> exists P. __INV_P(P) & __M_P(P)]
      TR_PROPH   = TR & PREV & PREV' & (forall P. __M_P(P) & __INV_P(P) & __INV_P'(P) -> __M_P'(P))
      PROPH_INV  = the prophecy invariants declared in the step's `by` block

The proof is incremental: PREV is the conjunction of all body invariants accumulated from
previous steps (empty for the first step). Each step's body invariants are added to PREV
after the step is verified, so later steps can rely on earlier ones and use earlier prophecy symbols.

After all steps, a final check verifies that the accumulated invariants establish
safety (BAD exclusion: INVARIANTS => SAFETY) or disjointness from init
(INIT exclusion: INVARIANTS => !INIT); at least one must hold.
This implies that no traces from init to bad exist, and thus the program is safe.

Prophecy invariants can be written explicitly as invariant formulas, or generated by heuristics:
  proph_default       — exists P. __INV_P(P) & __M_P(P)   (forward) / exists P. __INV_P(P) & !__M_P(P) (backward)
  proph_select theta  — encodes a choice: if theta holds, use proph_default; otherwise
                        require the prophecy relation to hold for all/no parameters; explicitly:
    forward:  (!theta -> forall P. __M_P(P))  & (theta -> exists P. __INV_P(P) & __M_P(P))
    backward: (!theta -> forall P. !__M_P(P)) & (theta -> exists P. __INV_P(P) & !__M_P(P))
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import List, Optional, Tuple

import utils
import syntax
from syntax import (
    Expr, SortedVar, InvariantDecl, FbiiDecl, FbiiStepDecl,
    And, Or, Not, Forall, Exists, Implies, New,
    AppExpr, Id, NaryExpr, TrueExpr,
    ConstantDecl, RelationDecl, ModifiesClause,
)
from logic import Solver, check_unsat
from semantics import Trace


# ---------------------------------------------------------------------------
# Complexity metrics
# ---------------------------------------------------------------------------

def _count_quantifiers(expr: Expr) -> int:
    """Count the total number of bound variables across all quantifiers."""
    if isinstance(expr, (syntax.Bool, syntax.Int, Id, AppExpr)):
        if isinstance(expr, AppExpr):
            return sum(_count_quantifiers(a) for a in expr.args)
        return 0
    elif isinstance(expr, syntax.UnaryExpr):
        return _count_quantifiers(expr.arg)
    elif isinstance(expr, syntax.BinaryExpr):
        return _count_quantifiers(expr.arg1) + _count_quantifiers(expr.arg2)
    elif isinstance(expr, NaryExpr):
        return sum(_count_quantifiers(a) for a in expr.args)
    elif isinstance(expr, syntax.QuantifierExpr):
        return len(expr.binder.vs) + _count_quantifiers(expr.body)
    elif isinstance(expr, syntax.IfThenElse):
        return (_count_quantifiers(expr.branch) + _count_quantifiers(expr.then)
                + _count_quantifiers(expr.els))
    elif isinstance(expr, syntax.Let):
        return _count_quantifiers(expr.val) + _count_quantifiers(expr.body)
    else:
        assert False, (type(expr), expr)


def _count_alternations(expr: Expr, cur_quant: Optional[str] = None, alts: int = 0, polarity: int = 1) -> int:
    """
    Count nested quantifier alternations, respecting polarity.
    Negation (and the antecedent of an implication) flips the effective quantifier type:
      forall X. !(forall Y. ...)  ==  forall X. exists Y. ...  => 1 alternation
      forall X. !(exists Y. ...)  ==  forall X. forall Y. ...  => 0 alternations
    Tracks the maximum alternations along any root-to-leaf path.
    """
    if isinstance(expr, syntax.QuantifierExpr):
        effective = expr.quant if polarity > 0 else ('EXISTS' if expr.quant == 'FORALL' else 'FORALL')
        new_alts = alts + (1 if cur_quant is not None and effective != cur_quant else 0)
        return _count_alternations(expr.body, effective, new_alts, polarity)
    elif isinstance(expr, (syntax.Bool, syntax.Int, Id)):
        return alts
    elif isinstance(expr, AppExpr):
        if not expr.args:
            return alts
        return max(_count_alternations(a, cur_quant, alts, polarity) for a in expr.args)
    elif isinstance(expr, syntax.UnaryExpr):
        new_pol = -polarity if expr.op == 'NOT' else polarity
        return _count_alternations(expr.arg, cur_quant, alts, new_pol)
    elif isinstance(expr, syntax.BinaryExpr):
        if expr.op == 'IMPLIES':
            return max(
                _count_alternations(expr.arg1, cur_quant, alts, -polarity),  # antecedent: flipped
                _count_alternations(expr.arg2, cur_quant, alts, polarity),
            )
        elif expr.op == 'IFF':
            # A <-> B appears in both polarities; take max over both
            return max(
                _count_alternations(expr.arg1, cur_quant, alts, polarity),
                _count_alternations(expr.arg1, cur_quant, alts, -polarity),
                _count_alternations(expr.arg2, cur_quant, alts, polarity),
                _count_alternations(expr.arg2, cur_quant, alts, -polarity),
            )
        else:
            return max(
                _count_alternations(expr.arg1, cur_quant, alts, polarity),
                _count_alternations(expr.arg2, cur_quant, alts, polarity),
            )
    elif isinstance(expr, NaryExpr):
        if not expr.args:
            return alts
        return max(_count_alternations(a, cur_quant, alts, polarity) for a in expr.args)
    elif isinstance(expr, syntax.IfThenElse):
        return max(
            _count_alternations(expr.branch, cur_quant, alts, polarity),
            _count_alternations(expr.then, cur_quant, alts, polarity),
            _count_alternations(expr.els, cur_quant, alts, polarity),
        )
    elif isinstance(expr, syntax.Let):
        return max(
            _count_alternations(expr.val, cur_quant, alts, polarity),
            _count_alternations(expr.body, cur_quant, alts, polarity),
        )
    else:
        assert False, (type(expr), expr)


def _count_boolean_connectives(expr: Expr) -> int:
    """Count binary boolean connectives: AND, OR, IMPLIES, IFF (negation excluded)."""
    if isinstance(expr, (syntax.Bool, syntax.Int, Id)):
        return 0
    elif isinstance(expr, AppExpr):
        return sum(_count_boolean_connectives(a) for a in expr.args)
    elif isinstance(expr, syntax.UnaryExpr):
        return _count_boolean_connectives(expr.arg)
    elif isinstance(expr, syntax.BinaryExpr):
        is_bool_op = expr.op in ('IMPLIES', 'IFF')
        return (1 if is_bool_op else 0) + _count_boolean_connectives(expr.arg1) + _count_boolean_connectives(expr.arg2)
    elif isinstance(expr, NaryExpr):
        is_bool_op = expr.op in ('AND', 'OR')
        # NaryExpr with n args contributes (n-1) binary connectives
        count = (len(expr.args) - 1) if is_bool_op else 0
        return count + sum(_count_boolean_connectives(a) for a in expr.args)
    elif isinstance(expr, syntax.QuantifierExpr):
        return _count_boolean_connectives(expr.body)
    elif isinstance(expr, syntax.IfThenElse):
        return (_count_boolean_connectives(expr.branch) + _count_boolean_connectives(expr.then)
                + _count_boolean_connectives(expr.els))
    elif isinstance(expr, syntax.Let):
        return _count_boolean_connectives(expr.val) + _count_boolean_connectives(expr.body)
    else:
        assert False, (type(expr), expr)


def _is_atom(expr: Expr) -> bool:
    """An atomic formula: relation application, equality/comparison, Bool, or Id (nullary relation)."""
    if isinstance(expr, (syntax.Bool, Id)):
        return True
    if isinstance(expr, AppExpr):
        return True
    if isinstance(expr, syntax.BinaryExpr) and expr.op in ('EQUAL', 'NOTEQ', 'GE', 'GT', 'LE', 'LT'):
        return True
    return False


def _is_literal(expr: Expr) -> bool:
    """An atom or its negation."""
    if isinstance(expr, syntax.UnaryExpr) and expr.op == 'NOT':
        return _is_atom(expr.arg)
    return _is_atom(expr)


def _is_cube(expr: Expr) -> bool:
    """
    True if expr has the structure of a cube, with quantifiers allowed anywhere.
    At each level, strips any leading quantifiers, then checks:
      - a literal
      - AND whose conjuncts are each cubes
      - NOT(clause)
    """
    while isinstance(expr, syntax.QuantifierExpr):
        expr = expr.body
    if _is_literal(expr):
        return True
    if isinstance(expr, NaryExpr) and expr.op == 'AND':
        return all(_is_cube(a) for a in expr.args)
    if isinstance(expr, syntax.UnaryExpr) and expr.op == 'NOT':
        return _is_clause(expr.arg)
    return False


def _is_clause(expr: Expr) -> bool:
    """
    True if expr has the structure of a clause, with quantifiers allowed anywhere.
    At each level, strips any leading quantifiers, then checks:
      - a literal
      - OR whose disjuncts are each clauses
      - NOT(cube)
      - cube -> clause
    """
    while isinstance(expr, syntax.QuantifierExpr):
        expr = expr.body
    if _is_literal(expr):
        return True
    if isinstance(expr, NaryExpr) and expr.op == 'OR':
        return all(_is_clause(a) for a in expr.args)
    if isinstance(expr, syntax.BinaryExpr) and expr.op == 'IMPLIES':
        return _is_cube(expr.arg1) and _is_clause(expr.arg2)
    if isinstance(expr, syntax.UnaryExpr) and expr.op == 'NOT':
        return _is_cube(expr.arg)
    return False


def _is_clausal(expr: Expr) -> bool:
    """
    True if expr has the structure of a conjunction of clauses.
    Strips outer FORALL quantifiers and outer AND conjunctions (recursively),
    then delegates to _is_clause.
    """
    if isinstance(expr, syntax.QuantifierExpr) and expr.quant == 'FORALL':
        return _is_clausal(expr.body)
    if isinstance(expr, NaryExpr) and expr.op == 'AND':
        return all(_is_clausal(a) for a in expr.args)
    return _is_clause(expr)


def _max_complexity(exprs: List[Expr]) -> Tuple[int, int, int, bool]:
    """
    Return (max_quantifiers, max_alternations, max_bool_connectives, all_clausal)
    across a non-empty list of expressions.
    """
    assert exprs
    max_q  = max(_count_quantifiers(e) for e in exprs)
    max_a  = max(_count_alternations(e) for e in exprs)
    max_nb = max(_count_boolean_connectives(e) for e in exprs)
    all_cl = all(_is_clausal(e) for e in exprs)
    return max_q, max_a, max_nb, all_cl


def _step_user_exprs(step: syntax.FbiiStepDecl) -> List[Expr]:
    """
    Collect all user-written expressions for a step: body invariants plus
    prophecy-block formulas as written by the user (InvariantDecl.expr, or
    the argument of a proph_select heuristic).
    """
    exprs: List[Expr] = [inv.expr for inv in step.body]
    if step.prophecy is not None:
        for item in step.prophecy:
            if isinstance(item, InvariantDecl):
                exprs.append(item.expr)
            elif isinstance(item, syntax.FbiiHeuristicDecl) and item.arg is not None:
                # proph_select theta — include the theta expression
                exprs.append(item.arg)
    return exprs


def print_fbii_predicate_complexity(prog: syntax.Program) -> None:
    """Print a single complexity table: one row for invariants, one row per FBII step."""
    # --- Collect rows ---
    # Each row: (label, max_q, max_a, max_nb, all_clausal, proph_params_str)
    Row = Tuple[str, int, int, int, bool, str]
    rows: List[Row] = []

    # Invariants row (non-safety)
    inv_exprs: List[Expr] = [inv.expr for inv in prog.invs() if not inv.is_safety]
    if inv_exprs:
        max_q, max_a, max_nb, all_cl = _max_complexity(inv_exprs)
        rows.append(('proof by invariant', max_q, max_a, max_nb, all_cl, '-'))

    # FBII step rows
    fbii_decls = list(prog.fbii_decls())
    for fbii_idx, fbii in enumerate(fbii_decls):
        prefix = f'fbii block {fbii_idx + 1},' if len(fbii_decls) > 1 else 'fbii'
        num_steps = len(fbii.steps)
        for step_idx, step in enumerate(fbii.steps):
            dir_str = step.direction + (' prophecy' if step.has_prophecy else '')
            direction = dir_str + ((f' [{step.name}]') if step.name else '')
            label = f'{prefix} {step_idx + 1}/{num_steps} ({direction})'
            exprs = _step_user_exprs(step)
            if exprs:
                max_q, max_a, max_nb, all_cl = _max_complexity(exprs)
            else:
                max_q, max_a, max_nb, all_cl = 0, 0, 0, True
            pp = str(len(step.params)) if step.has_prophecy else '-'
            rows.append((label, max_q, max_a, max_nb, all_cl, pp))

    if not rows:
        utils.logger.always_print('(no invariants or fbii blocks found)')
        return

    # --- Print table ---
    lbl_w = max(len(r[0]) for r in rows)
    sep = (f'  {"-" * lbl_w}  {"-" * 11}  {"-" * 12}'
           f'  {"-" * 9}  {"-" * 7}  {"-" * 12}')
    utils.logger.always_print(
        f'  {"":<{lbl_w}}  {"quantifiers":>11}  {"alternations":>12}'
        f'  {"bool-conn":>9}  {"clausal":>7}  {"proph-params":>12}'
    )
    utils.logger.always_print(sep)
    for label, max_q, max_a, max_nb, all_cl, pp in rows:
        utils.logger.always_print(
            f'  {label:<{lbl_w}}  {max_q:>11}  {max_a:>12}'
            f'  {max_nb:>9}  {"yes" if all_cl else "no":>7}  {pp:>12}'
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def split_conjuncts(expr: Expr) -> List[Expr]:
    """Recursively flatten nested AND nodes into a list of conjuncts."""
    if isinstance(expr, NaryExpr) and expr.op == 'AND':
        result: List[Expr] = []
        for arg in expr.args:
            result.extend(split_conjuncts(arg))
        return result
    return [expr]


def _subst_inv_p_in_expr(
        expr: Expr,
        params: Tuple[SortedVar, ...],
        body_invs: List[InvariantDecl],
        scope: syntax.Scope,
) -> Expr:
    """
    Walk expr replacing every __INV_P(args...) application with the conjunction
    of body invariants with params substituted by args.
    Also replace nullary __INV_P (Id node) when there are no params.
    """
    if isinstance(expr, syntax.Bool) or isinstance(expr, syntax.Int):
        return expr
    elif isinstance(expr, syntax.UnaryExpr):
        return syntax.UnaryExpr(expr.op, _subst_inv_p_in_expr(expr.arg, params, body_invs, scope), span=expr.span)
    elif isinstance(expr, syntax.BinaryExpr):
        return syntax.BinaryExpr(
            expr.op,
            _subst_inv_p_in_expr(expr.arg1, params, body_invs, scope),
            _subst_inv_p_in_expr(expr.arg2, params, body_invs, scope),
            span=expr.span,
        )
    elif isinstance(expr, NaryExpr):
        return NaryExpr(
            expr.op,
            tuple(_subst_inv_p_in_expr(a, params, body_invs, scope) for a in expr.args),
            span=expr.span,
        )
    elif isinstance(expr, AppExpr):
        if expr.callee == '__INV_P':
            # Replace __INV_P(args) with INV(args), i.e., body conjuncts with P -> args
            assert len(expr.args) == len(params), \
                f'__INV_P applied to {len(expr.args)} args but step has {len(params)} params'
            gamma = {Id(sv.name): arg for sv, arg in zip(params, expr.args)}
            conjs = [syntax.subst(scope, inv.expr, gamma) for inv in body_invs]
            return And(*conjs)
        else:
            return AppExpr(
                expr.callee,
                tuple(_subst_inv_p_in_expr(a, params, body_invs, scope) for a in expr.args),
                n_new=expr.n_new,
                span=expr.span,
            )
    elif isinstance(expr, Id):
        if expr.name == '__INV_P' and len(params) == 0:
            return And(*[inv.expr for inv in body_invs])
        return expr
    elif isinstance(expr, syntax.QuantifierExpr):
        new_body = _subst_inv_p_in_expr(expr.body, params, body_invs, scope)
        return syntax.QuantifierExpr(expr.quant, expr.binder.vs, new_body, span=expr.span)
    elif isinstance(expr, syntax.IfThenElse):
        return syntax.IfThenElse(
            _subst_inv_p_in_expr(expr.branch, params, body_invs, scope),
            _subst_inv_p_in_expr(expr.then, params, body_invs, scope),
            _subst_inv_p_in_expr(expr.els, params, body_invs, scope),
            span=expr.span,
        )
    elif isinstance(expr, syntax.Let):
        return syntax.Let(
            expr.binder.vs[0],
            _subst_inv_p_in_expr(expr.val, params, body_invs, scope),
            _subst_inv_p_in_expr(expr.body, params, body_invs, scope),
            span=expr.span,
        )
    else:
        assert False, (type(expr), expr)


def build_pinv_conjuncts(
        step: FbiiStepDecl,
        scope: syntax.Scope,
) -> List[Expr]:
    """
    Build the list of prophecy conjuncts for a step.

    If the step has a prophecy block: apply __INV_P substitution and split.
    Otherwise: build the default PINV based on direction.
    """
    params = step.params
    body_invs = step.body
    inv_conj = And(*[inv.expr for inv in body_invs])

    if step.prophecy is not None:
        # Substitute __INV_P in each prophecy item, collect all conjuncts
        result: List[Expr] = []
        for item in step.prophecy:
            if isinstance(item, syntax.FbiiHeuristicDecl):
                raw_expr = _expand_heuristic(item, step.direction, params)
            else:
                raw_expr = item.expr
            subst_expr = _subst_inv_p_in_expr(raw_expr, params, body_invs, scope)
            result.extend(split_conjuncts(subst_expr))
        return result if result else [TrueExpr]
    else:
        # Default prophecy invariants:
        mp_app = _mp_app(params)
        if step.direction == 'forward':
            default = Exists(params, And(inv_conj, mp_app))
        else:
            default = Exists(params, And(inv_conj, Not(mp_app)))
        return split_conjuncts(default)


def _mp_app(params: Tuple[SortedVar, ...]) -> Expr:
    if params:
        return AppExpr('__M_P', tuple(Id(p.name) for p in params))
    else:
        return Id('__M_P')


def _inv_p_app(params: Tuple[SortedVar, ...]) -> Expr:
    if params:
        return AppExpr('__INV_P', tuple(Id(p.name) for p in params))
    else:
        return Id('__INV_P')


def _expand_heuristic(
        heuristic: syntax.FbiiHeuristicDecl,
        direction: str,
        params: Tuple[SortedVar, ...],
) -> Expr:
    """Expand a prophecy heuristic to an expression (may contain __INV_P and __M_P)."""
    mp = _mp_app(params)
    inv_p = _inv_p_app(params)
    if heuristic.name == 'proph_default':
        # Default: exists P. __INV_P(P) & __M_P(P)  (forward)
        #          exists P. __INV_P(P) & !__M_P(P) (backward)
        if direction == 'forward':
            return Exists(params, And(inv_p, mp))
        else:
            return Exists(params, And(inv_p, Not(mp)))
    elif heuristic.name == 'proph_select':
        # proph_select theta:
        #   forward:  (!theta -> forall P. __M_P(P))  & (theta -> exists P. __INV_P(P) & __M_P(P))
        #   backward: (!theta -> forall P. !__M_P(P)) & (theta -> exists P. __INV_P(P) & !__M_P(P))
        assert heuristic.arg is not None
        theta = heuristic.arg
        if direction == 'forward':
            return And(
                Implies(Not(theta), Forall(params, mp)),
                Implies(theta, Exists(params, And(inv_p, mp))),
            )
        else:
            return And(
                Implies(Not(theta), Forall(params, Not(mp))),
                Implies(theta, Exists(params, And(inv_p, Not(mp)))),
            )
    else:
        assert False, f'unknown heuristic: {heuristic.name!r}'


# ---------------------------------------------------------------------------
# Verification condition checks
# ---------------------------------------------------------------------------

class _FbiiFailure(Exception):
    """Raised on the first failing FBII check to terminate the proof immediately."""
    pass


def _check(
        s: Solver,
        num_states: int,
        hyps: List[Expr],
        neg_conc: Expr,
        label: str,
        verbose_lines: Optional[List[str]] = None,
        *,
        _silent: bool = False,
) -> None:
    """
    Check validity of (And(*hyps) => conc) by checking unsat of (And(*hyps) & !conc).
    Raises _FbiiFailure if the check fails (sat).
    If verbose_lines is provided and --verbose is set, those lines are printed after the label.
    If _silent is True, suppresses the per-check header and ok. line; on failure prints
    'no! (at: {label})' with the counterexample. Used for group summaries.
    """
    t = s.get_translator(num_states)
    if not _silent:
        utils.logger.always_print(f'  checking {label}')
        if verbose_lines and utils.args.verbose:
            for line in verbose_lines:
                utils.logger.always_print(f'    {line}')
    with s.new_frame():
        for h in hyps:
            s.add(t.translate_expr(h))
        s.add(t.translate_expr(neg_conc))
        m = check_unsat([], s, num_states, verbose=not _silent)
        if m is not None:
            if _silent:
                utils.logger.always_print(f'no! (at: {label})')
                if utils.args.print_counterexample:
                    utils.logger.always_print(f'\ncounterexample:\n{utils.indent(str(m))}')
            raise _FbiiFailure(label)


def _check_initiation_batch(
        s: Solver,
        hyps: List[Expr],
        conjuncts: List[Expr],
        conj_name: str,
        title: str,
        formula: str,
        verbose: bool,
) -> None:
    """Check ``hyps => ci`` for each ci.

    Hypotheses are pushed once in an outer frame so Z3 can reuse learned
    clauses about them across all per-conjunct queries.
    """
    t = s.get_translator(1)
    n = len(conjuncts)
    utils.logger.always_print(f'  checking {title} ({formula})')
    _t = datetime.now()
    with s.new_frame():
        for h in hyps:
            s.add(t.translate_expr(h))
        for i, ci in enumerate(conjuncts):
            label = f'{title} (conjunct {i + 1}/{n}): {formula}'
            if verbose:
                utils.logger.always_print(f'    {conj_name}[{i + 1}/{n}]: {ci}... ', end='')
            _t_ci = datetime.now()
            with s.new_frame():
                s.add(t.translate_expr(Not(ci)))
                m = check_unsat([], s, 1, verbose=False)
                if m is not None:
                    if verbose:
                        utils.logger.always_print(f'no!')
                    else:
                        utils.logger.always_print(f'no! (at: {label})')
                    if utils.args.print_counterexample:
                        utils.logger.always_print(f'\ncounterexample:\n{utils.indent(str(m))}')
                    raise _FbiiFailure(label)
            if verbose:
                utils.logger.always_print(f'ok. ({datetime.now() - _t_ci})')
    if verbose:
        utils.logger.always_print(f'  ok. ({datetime.now() - _t})')
    else:
        utils.logger.always_print(f'ok. ({datetime.now() - _t})')


def _check_consecution_batch(
        s: Solver,
        prog: syntax.Program,
        base_hyps: List[Expr],
        conjuncts: List[Expr],
        prime_conc: bool,
        conj_name: str,
        title: str,
        formula: str,
        verbose: bool,
        extra_mods: Tuple[syntax.ModifiesClause, ...] = (),
) -> None:
    """Check consecution across all transitions.

    Uses three nested frames mirroring ``verify``'s structure:
      outer  — base hypotheses (pushed once, shared across all transitions)
      middle — transition formula (pushed once per transition, shared across conjuncts)
      inner  — negated conclusion (pushed once per conjunct)
    """
    t = s.get_translator(2)
    n = len(conjuncts)
    if not verbose:
        utils.logger.always_print(f'  checking {title} ({formula})')
    _t = datetime.now()
    with s.new_frame():
        for h in base_hyps:
            s.add(t.translate_expr(h))
        for ition in prog.transitions():
            tr_expr = ition.as_twostate_formula(prog.scope, extra_mods=extra_mods)
            if verbose:
                utils.logger.always_print(f'  checking {title} (transition {ition.name}): {formula}')
            _t_tr = datetime.now()
            with s.new_frame():
                s.add(t.translate_expr(tr_expr))
                for i, ci in enumerate(conjuncts):
                    label = f'{title} (transition {ition.name}, conjunct {i + 1}/{n}): {formula}'
                    neg_conc = Not(New(ci)) if prime_conc else Not(ci)
                    if verbose:
                        utils.logger.always_print(f'    {conj_name}[{i + 1}/{n}]: {ci}... ', end='')
                    _t_ci = datetime.now()
                    with s.new_frame():
                        s.add(t.translate_expr(neg_conc))
                        m = check_unsat([], s, 2, verbose=False)
                        if m is not None:
                            if verbose:
                                utils.logger.always_print(f'no!')
                            else:
                                utils.logger.always_print(f'no! (at: {label})')
                            if utils.args.print_counterexample:
                                utils.logger.always_print(f'\ncounterexample:\n{utils.indent(str(m))}')
                            raise _FbiiFailure(label)
                    if verbose:
                        utils.logger.always_print(f'ok. ({datetime.now() - _t_ci})')
            if verbose:
                utils.logger.always_print(f'  ok. ({datetime.now() - _t_tr})')
    if not verbose:
        utils.logger.always_print(f'ok. ({datetime.now() - _t})')


# ---------------------------------------------------------------------------
# Main checker
# ---------------------------------------------------------------------------

def check_fbii(s: Solver) -> None:
    prog = syntax.the_program

    fbii_decls = list(prog.fbii_decls())
    if not fbii_decls:
        utils.logger.always_print('warning: no fbii blocks found')
        return

    for fbii in fbii_decls:
        try:
            _check_fbii_proof(s, prog, prog.scope, fbii)
        except _FbiiFailure:
            utils.exit(1)
            return
        utils.logger.always_print(
            '\nprogram proven SAFE via forward-backward incremental induction with prophecy'
        )


def _check_step_simple(
        s: Solver,
        prog: syntax.Program,
        direction: str,
        init_expr: Expr,
        bad_expr: Expr,
        prev: Expr,
        inv_conj: Expr,
        verbose: bool,
) -> None:
    """Simple step: plain induction (no prophecy variable needed)."""
    inv_conjuncts = split_conjuncts(inv_conj)
    if direction == 'forward':
        _check_initiation_batch(
            s, hyps=[init_expr, prev], conjuncts=inv_conjuncts, conj_name='INV',
            title='forward invariant initiation', formula='INIT & PREV => INV', verbose=verbose,
        )
        _check_consecution_batch(
            s, prog, base_hyps=[inv_conj, prev, New(prev)], conjuncts=inv_conjuncts,
            prime_conc=True, conj_name='INV',
            title='forward invariant consecution', formula="INV & TR & PREV & PREV' => INV'",
            verbose=verbose,
        )
    else:  # backward
        _check_initiation_batch(
            s, hyps=[bad_expr, prev], conjuncts=inv_conjuncts, conj_name='INV',
            title='backward invariant initiation', formula='BAD & PREV => INV', verbose=verbose,
        )
        _check_consecution_batch(
            s, prog, base_hyps=[New(inv_conj), prev, New(prev)], conjuncts=inv_conjuncts,
            prime_conc=False, conj_name='INV',
            title='backward invariant consecution', formula="INV' & TR & PREV & PREV' => INV",
            verbose=verbose,
        )


def _check_step_prophecy(
        s: Solver,
        prog: syntax.Program,
        scope: syntax.Scope,
        step: FbiiStepDecl,
        init_expr: Expr,
        bad_expr: Expr,
        prev: Expr,
        inv_conj: Expr,
        verbose: bool,
) -> None:
    """Prophecy-based path: build PINV and run 3 checks with __M_P."""
    params = step.params
    pinv_conjuncts = build_pinv_conjuncts(step, scope)
    pinv = And(*pinv_conjuncts)

    mp = _mp_app(params)
    init_proph = And(init_expr, prev, Forall(params, Implies(inv_conj, mp)))
    bad_proph  = And(bad_expr,  prev, Forall(params, Implies(inv_conj, Not(mp))))
    tr_proph   = And(prev, New(prev), Forall(params, Implies(And(mp, inv_conj, New(inv_conj)), New(mp))))

    n = len(pinv_conjuncts)
    verbose_pinv = [f'PROPH_INV[{j + 1}/{n}]: {c}' for j, c in enumerate(pinv_conjuncts)]

    if step.direction == 'forward':
        _check_initiation_batch(
            s, hyps=[init_proph], conjuncts=pinv_conjuncts, conj_name='PROPH_INV',
            title='forward prophecy initiation', formula='INIT_PROPH => PROPH_INV', verbose=verbose,
        )
        _check_consecution_batch(
            s, prog, base_hyps=[pinv, tr_proph], conjuncts=pinv_conjuncts,
            prime_conc=True, conj_name='PROPH_INV',
            title='forward prophecy consecution', formula="PROPH_INV & TR_PROPH => PROPH_INV'",
            verbose=verbose, extra_mods=(ModifiesClause('__M_P'),),
        )
        _check(s, 1, hyps=[pinv], neg_conc=bad_proph,
               label='forward prophecy safety (PROPH_INV => !BAD_PROPH)', verbose_lines=verbose_pinv)
    else:  # backward
        _check_initiation_batch(
            s, hyps=[bad_proph], conjuncts=pinv_conjuncts, conj_name='PROPH_INV',
            title='backward prophecy initiation', formula='BAD_PROPH => PROPH_INV', verbose=verbose,
        )
        _check_consecution_batch(
            s, prog, base_hyps=[New(pinv), tr_proph], conjuncts=pinv_conjuncts,
            prime_conc=False, conj_name='PROPH_INV',
            title='backward prophecy consecution', formula="PROPH_INV' & TR_PROPH => PROPH_INV",
            verbose=verbose, extra_mods=(ModifiesClause('__M_P'),),
        )
        _check(s, 1, hyps=[pinv], neg_conc=init_proph,
               label='backward prophecy safety (PROPH_INV => !INIT_PROPH)', verbose_lines=verbose_pinv)


def _check_fbii_proof(
        s: Solver,
        prog: syntax.Program,
        scope: syntax.Scope,
        fbii: FbiiDecl,
) -> None:
    prev_formulas: List[Expr] = []
    num_steps = len(fbii.steps)

    init_expr = And(*[init.expr for init in prog.inits()])
    safety_expr = And(*[safety_decl.expr for safety_decl in prog.safeties()])
    bad_expr = Not(safety_expr)

    for step_idx, step in enumerate(fbii.steps):
        utils.logger.always_print(
            f'\nchecking fbii step {step_idx + 1}/{num_steps} '
            f'({step.direction}{(" [" + step.name + "]") if step.name else ""})'
        )

        params = step.params
        body_invs = step.body
        inv_conj: Expr = And(*[inv.expr for inv in body_invs])
        prev = And(*prev_formulas)
        verbose = getattr(utils.args, 'verbose', False)

        try:
            if not step.has_prophecy:
                _check_step_simple(s, prog, step.direction, init_expr, bad_expr, prev, inv_conj, verbose)
            else:
                param_sorts = tuple(syntax.safe_cast_sort(sv.sort) for sv in params)
                mp_decl = RelationDecl('__M_P', param_sorts, mutable=True)
                with scope.temp_relations(mp_decl):
                    _check_step_prophecy(s, prog, scope, step, init_expr, bad_expr, prev, inv_conj, verbose)
            utils.logger.always_print(f'  step {step_idx + 1} OK')
        except _FbiiFailure:
            utils.logger.always_print(f'  step {step_idx + 1} FAILED')
            raise

        prev_formulas.extend(inv.expr for inv in body_invs)

        # Promote this step's prophecy params to immutable constants in scope
        # so that subsequent steps can reference them in their formulas.
        for sv in step.params:
            actual_sort = syntax.safe_cast_sort(sv.sort)
            scope.constants[sv.name] = ConstantDecl(sv.name, actual_sort, mutable=False)

    inv_all = And(*prev_formulas)
    if not _run_final_checks(s, init_expr, safety_expr, inv_all, fbii.span):
        raise _FbiiFailure('final checks')


def _run_final_checks(
        s: Solver,
        init_expr: Expr,
        safety_expr: Expr,
        prev: Expr,
        span: Optional[syntax.Span],
) -> bool:
    """
    Run BAD exclusion and INIT exclusion final checks.
    Returns True if at least one passes; prints the error and returns False if both fail.
    """
    utils.logger.always_print('')
    utils.logger.always_print('final step (BAD exclusion or INIT exclusion must hold):')

    utils.logger.always_print('  checking BAD exclusion: INVARIANTS => SAFETY')
    bad_excl_model, bad_excl_elapsed = _silent_final_check(s, prev, safety_expr)
    if bad_excl_model is None:
        utils.logger.always_print(f'  BAD exclusion: ok. ({bad_excl_elapsed})')
        return True

    utils.logger.always_print('  BAD exclusion: no!')

    utils.logger.always_print('  checking INIT exclusion: INVARIANTS => !INIT')
    init_excl_model, init_excl_elapsed = _silent_final_check(s, prev, Not(init_expr))
    if init_excl_model is None:
        utils.logger.always_print(f'  INIT exclusion: ok. ({init_excl_elapsed})')
        return True

    utils.logger.always_print('  INIT exclusion: no!')
    if utils.args.print_counterexample:
        utils.logger.always_print('\ncounterexample for BAD exclusion:')
        utils.logger.always_print(utils.indent(str(bad_excl_model)))
        utils.logger.always_print('\ncounterexample for INIT exclusion:')
        utils.logger.always_print(utils.indent(str(init_excl_model)))
    utils.print_error(span, 'fbii proof: final step does not establish safety or disjointness from init')
    return False


def _silent_final_check(s: Solver, prev: Expr, conc: Expr) -> Tuple[Optional[Trace], timedelta]:
    """
    Silently check PREV => CONC (i.e., unsat of PREV & !CONC).
    Returns (model, elapsed_time). model is None if the check passes (unsat).
    """
    t = s.get_translator(1)
    with s.new_frame():
        s.add(t.translate_expr(And(prev, Not(conc))))
        start = datetime.now()
        m = check_unsat([], s, 1, verbose=False)
        elapsed = datetime.now() - start
    return m, elapsed
